# Generated by Django 5.0.3 on 2024-04-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_details',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
