# Generated by Django 5.0.3 on 2024-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
