# Generated by Django 5.0.3 on 2024-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_profile_picture_url_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_profile_picture',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
