# Generated by Django 5.0.3 on 2024-04-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketly', '0009_remove_cart_products_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('InCart', 'Incart'), ('Pending', 'Pending'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
