# Generated by Django 5.0.3 on 2024-04-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketly', '0010_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
