# Generated by Django 5.0.3 on 2024-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketly', '0011_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_picture_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
