# Generated by Django 5.0.3 on 2024-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketly', '0016_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
