# Generated by Django 5.0.3 on 2024-05-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketly', '0019_comparelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketly.comparelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketly.product')),
            ],
        ),
    ]
